# SPDX-FileCopyrightText: Josef Andersson
#
# SPDX-License-Identifier: CC0-1.0

# Description:
# This workflow hardens the GitHub Actions runner by restricting egress traffic.
# It helps improve security by limiting outbound network access during workflow execution.
#
# Usage:
# 1. Add the following to your workflow file:
#    jobs:
#      harden-runner:
#        uses: ./.github/workflows/harden-runner.yml
#        with:
#          egress-policy: "audit" # Optional, default is "audit"
#
# 2. The workflow will harden the runner based on the specified egress policy.
#    - Use "audit" to log egress traffic without blocking it.
#    - Use "block" to block all egress traffic except for allowed domains.
---
name: "Harden Runner"

on: 
  workflow_call:
    inputs:
      egress-policy:
        description: "Egress policy for the Harden Runner step (e.g., audit, block)"
        required: false
        default: "audit"
        type: string

permissions:
  contents: read

jobs:
  harden-runner:
    name: Harden GitHub Runner
    runs-on: ubuntu-latest
    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: ${{ inputs.egress-policy }}
